services:
  supabase-ai-assistant:
    container_name: supabase-ai-assistant
    image: kocur.app/supabase-ai-assistant:latest
    build:
      dockerfile: dockerfile.prod
      args:
        - PORT=7202
        - NODE_ENV=production
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - API_SECRET=${API_SECRET}
    ports:
      - "7201:7202"
    environment:
      - PORT=7202
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_SECRET=${API_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.supabase-ai-assistant.rule=Host(`${API_PROD_URL}`) && PathPrefix(`/trigger-ai-assistant`)
      - traefik.http.routers.supabase-ai-assistant.tls=true
      - traefik.http.routers.supabase-ai-assistant.tls.certresolver=letsencrypt
      - traefik.http.services.supabase-ai-assistant.loadbalancer.server.port=7202
      - traefik.http.middlewares.supabase-ai-assistant-timeout.headers.customrequestheaders.X-Timeout=60
      - traefik.http.routers.supabase-ai-assistant.middlewares=supabase-ai-assistant-timeout
    networks:
      - proxy
    volumes:
      - /app/node_modules
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    driver: bridge
    external: true
    name: proxy
